# Generated by Django 4.2.3 on 2023-07-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_imagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagem_produto'),
            preserve_default=False,
        ),
    ]
